services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Password1512@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  webapp:
    build:
      context: .
    container_name: recruitmentapp
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DbContext=Server=sqlserver;Database=db_recruitment;User Id=sa;Password=Password1512@;
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
