version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    networks:
      - backend

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MyAppDb;User Id=sa;Password=YourStrong!Passw0rd;"
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - backend

networks:
  backend:
    driver: bridge
